[project]
name = "ticket-triage-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jerome Embate" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "numpy>=2.5.2",
    "pydantic>=2.13.5",
    "pydantic-ai>=2.37.0",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.1",
]

[project.scripts]
ticket-triage-agent = "ticket_triage_agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
