name: Build and Push App to ECR

on:
  push:
    branches:
    - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    # - name: Debug OIDC token
    #   run: |
    #     OIDC_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
    #       "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r .value)

    #     # Decode claims (header.payload.signature)
    #     echo "$OIDC_TOKEN" | cut -d. -f2 | base64 -d 2>/dev/null | jq
    #     # Look at: sub, aud, ref, environment

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        audience: sts.amazonaws.com
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_IAM_ROLE }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Release new version
      id: release
      run: |
        bash ./scripts/git_update.sh -v patch

    - name: Add app version (Optional)
      run: echo ${{ steps.release.outputs.new-tag }} > version.txt

    - name: Build, tag, and push Docker image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ github.repository }}
        IMAGE_TAG: ${{ steps.release.outputs.new-tag }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
